name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
          - os-name: macOS-arm64
            runs-on: macos-latest
            target: aarch64-apple-darwin
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.runs-on }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [ "${{ matrix.platform.runs-on }}" == "windows-latest" ]; then
            7z a ../../../dex-parser-${{ matrix.platform.os-name }}.zip dex-parser-rust.exe
          else
            tar czf ../../../dex-parser-${{ matrix.platform.os-name }}.tar.gz dex-parser-rust
          fi
          cd -

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dex-parser-*.tar.gz
            dex-parser-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
